import 'package:food_bridge/controller/authcontroller.dart';
import 'package:food_bridge/controller/backgroundservice.dart';
import 'package:food_bridge/controller/notificationservice.dart';
import 'package:food_bridge/controller/donationcontroller.dart';
import 'package:food_bridge/controller/localizationcontroller.dart';
import 'package:food_bridge/controller/notificationcontroller.dart';
import 'package:food_bridge/controller/usercontroller.dart';
import 'package:food_bridge/controller/widget_controller/bottombuttoncontroller.dart';
import 'package:food_bridge/controller/widget_controller/datetimepickercontroller.dart';
import 'package:food_bridge/controller/widget_controller/distanceslidercontroller.dart';
import 'package:food_bridge/controller/widget_controller/finddonationfiltercontroller.dart';
import 'package:food_bridge/controller/widget_controller/foodtypecheckboxcontroller.dart';
import 'package:food_bridge/controller/widget_controller/likebuttoncontroller.dart';
import 'package:food_bridge/controller/widget_controller/limitcontroller.dart';
import 'package:food_bridge/controller/widget_controller/mapcontroller.dart';
import 'package:food_bridge/controller/widget_controller/passwordtextfieldcontroller.dart';
import 'package:food_bridge/controller/widget_controller/quantitycontroller.dart';
import 'package:food_bridge/controller/widget_controller/receivingdialogcontroller.dart';
import 'package:food_bridge/controller/widget_controller/reviewdialogcontroller.dart';
import 'package:food_bridge/controller/widget_controller/rolebuttoncontroller.dart';

final mapController = MapController();
final authController = AuthController();
final userController = UserController();
final limitController = LimitController();
final filterController = FilterController();
final backgroundService = BackgroundService();
final quantityController = QuantityController();
final donationController = DonationController();
final notificationService = NotificationService();
final reviewController = ReviewDialogController();
final localeController = LocalizationController();
final roleButtonController = RoleButtonController();
final likeButtonController = LikeButtonController();
final bottomButtonController = BottomButtonController();
final notificationController = NotificationController();
final distanceSliderController = DistanceSliderController();
final dateTimePickerController = DatetimePickerController();
final receivingDialogController = ReceivingDialogController();
final foodCategoryController = FoodCategoryCheckBoxController();
final passwordTextFieldController = PasswordTextfieldController();
